### ISSUE TITLE
feat(app): encrypt data

### ISSUE THREAD

**Issue by huilensolis** [Huilensolis/memoir#217]
learn AES encryption

**Comment by huilensolis** [comment]
- [ ] Use AES to encrypt user data before sending to the server.
- [ ] Use plaintext user passwords as encryption key, ask them for long passwords.
- [ ] Only send hashed passwords to your server (don't forget to salt them too; ideally use bcrypt, it does that for you).
- [ ] Hash passwords on the server again so database dumps aren't enough to log into user accounts (again use bcrypt).
- [ ] Use base64 to encode encrypted payloads so you can treat them as simple strings in your database.

**Comment by guiprav2** [comment]
`encrypt/decrypt` utilities example:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AES Encryption/Decryption</title>
    <script>
        async function getKeyMaterial(password) {
            const encoder = new TextEncoder();
            return window.crypto.subtle.importKey(
                "raw",
                encoder.encode(password),
                { name: "PBKDF2" },
                false,
                ["deriveKey"]
            );
        }

        async function getKey(keyMaterial, salt) {
            return window.crypto.subtle.deriveKey(
                {
                    name: "PBKDF2",
                    salt: salt,
                    iterations: 100000,
                    hash: "SHA-256"
                },
                keyMaterial,
                { name: "AES-GCM", length: 256 },
                false,
                ["encrypt", "decrypt"]
            );
        }

        function arrayBufferToBase64(buffer) {
            let binary = '';
            const bytes = new Uint8Array(buffer);
            const len = bytes.byteLength;
            for (let i = 0; i < len; i++) {
                binary += String.fromCharCode(bytes[i]);
            }
            return window.btoa(binary);
        }

        function base64ToArrayBuffer(base64) {
            const binary = window.atob(base64);
            const len = binary.length;
            const bytes = new Uint8Array(len);
            for (let i = 0; i < len; i++) {
                bytes[i] = binary.charCodeAt(i);
            }
            return bytes.buffer;
        }

        async function encrypt(payload, password) {
            const keyMaterial = await getKeyMaterial(password);
            const salt = window.crypto.getRandomValues(new Uint8Array(16));
            const key = await getKey(keyMaterial, salt);
            const iv = window.crypto.getRandomValues(new Uint8Array(12));
            const encoder = new TextEncoder();
            const data = encoder.encode(payload);
            const encryptedData = await window.crypto.subtle.encrypt(
                {
                    name: "AES-GCM",
                    iv: iv
                },
                key,
                data
            );
            const encryptedContent = new Uint8Array(encryptedData);
            const result = new Uint8Array(salt.length + iv.length + encryptedContent.length);
            result.set(salt, 0);
            result.set(iv, salt.length);
            result.set(encryptedContent, salt.length + iv.length);
            return arrayBufferToBase64(result.buffer);
        }

        async function decrypt(payload, password) {
            const keyMaterial = await getKeyMaterial(password);
            const data = base64ToArrayBuffer(payload);
            const salt = data.slice(0, 16);
            const iv = data.slice(16, 28);
            const encryptedData = data.slice(28);
            const key = await getKey(keyMaterial, salt);
            const decryptedData = await window.crypto.subtle.decrypt(
                {
                    name: "AES-GCM",
                    iv: iv
                },
                key,
                encryptedData
            );
            const decoder = new TextDecoder();
            return decoder.decode(decryptedData);
        }

        // Example usage:
        async function exampleUsage() {
            const text = "Hello, world!";
            const password = "securepassword";
            const encrypted = await encrypt(text, password);
            console.log("Encrypted:", encrypted);
            const decrypted = await decrypt(encrypted, password);
            console.log("Decrypted:", decrypted);
        }

        window.onload = exampleUsage;
    </script>
</head>
<body>
    <h1>AES Encryption/Decryption Example</h1>
    <p>Check the console for results.</p>
</body>
</html>
```

**Comment by huilensolis** [comment]
### Step-by-Step Encryption Implementation TODO

1. **Research and Choose Encryption Algorithm**:
   - [ ] Study encryption algorithms (e.g., AES) and select one suitable for client-side encryption.
   - [ ] Ensure the chosen algorithm is supported by the Web Crypto API.

2. **Generate Encryption Key**:
   - [ ] Generate a random string on the client-side using a cryptographically secure method (e.g., `window.crypto.getRandomValues()`).
   - [ ] Use the random string to derive a secure encryption key with a key derivation function (e.g., PBKDF2, HKDF).
   - [ ] Prompt the user to store this random string securely (e.g., in a file or on paper).

3. **Implement Document Encryption**:
   - [ ] Use the Web Crypto API to encrypt document content with the derived key.
   - [ ] Ensure that encryption happens on the client before sending data to the server.

4. **Implement Document Decryption**:
   - [ ] Use the Web Crypto API to decrypt documents on the client with the stored key.
   - [ ] Provide a UI for users to input the key if they are accessing the document from a new device.
   - [ ] Ensure decryption works reliably and only for authorized users.

5. **Key Storage (Secure)**:
   - [ ] **Temporary Storage**: Store the encryption key in memory during a session (not in `localStorage`).
   - [ ] Implement secure key handling to prevent exposing the key to unauthorized scripts (e.g., avoid XSS vulnerabilities).
   - [ ] Research secure storage options (e.g., Web Crypto's `SubtleCrypto`, IndexedDB) for longer sessions or to improve usability.

7. **Backup/Recovery Mechanism** (Optional):
   - [ ] Design a backup mechanism for users who may lose their encryption key.
   - [ ] Optionally encrypt the key itself and store it securely on the server, allowing users to recover it after authenticating.

8. **User Interface for Key Management**:
   - [ ] Create a simple interface to allow users to manage their encryption key.
   - [ ] Provide instructions to users for securely storing their key.

11. **Documentation**:
    - [ ] Document how encryption works for users.
    - [ ] Provide clear recovery steps in case users lose access to their key.
